groups:
  - name: Kafka Alerts
    rules:
      - alert: KafkaHighRequestLatency
        expr: kafka_request_latency_ms > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency in Kafka topic '{{ $labels.topic }}'"
          description: "Request latency is above 100ms for more than 1 minute."